### ISSUE TITLE
variable "options" undefined

### ISSUE THREAD

**Issue by duebbert** [davidchouse/Leaflet.NavBar#3]
doesn't work in strict mode on IE11 because `options` in `onAdd` is missing a `var`.

Line 26: https://github.com/davidchouse/Leaflet.NavBar/blob/master/src/Leaflet.NavBar.js#L26
`options = this.options;`
should be 
`var options = this.options;`

**Comment by davidchouse** [comment]
Thanks for the catch @duebbert.
